services:
  backend:
    build: 
      context: ${BACKEND_PATH:-../../BackEnd}
      dockerfile: Dockerfile
    container_name: my-backend-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ../../BackEnd/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - ../../BackEnd/.env
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../mysql/DataSpringBoots_BE.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

volumes:
  mysql-data: